// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
declare global {
  namespace App {
    interface Platform {
      env: Env;
      cf: CfProperties;
      ctx: ExecutionContext;
    }
  }
  namespace svelteHTML {
    interface IntrinsicElements {
      stack: IntrinsicElements["div"];
      row: IntrinsicElements["div"];
    }
    interface HTMLAttributes<T>
      extends Partial<Record<UnocssAttributes | CustomAttributes, string | boolean>> {}
  }
}

type CustomAttributes = "base";

type UnocssAttributes =
  | "aspect"
  | "container"
  | "columns"
  | "break-after"
  | "break-before"
  | "break-inside"
  | "box-decoration"
  | "box"
  | "block"
  | "inline-block"
  | "inline"
  | "flex"
  | "inline-flex"
  | "table"
  | "inline-table"
  | "table-caption"
  | "table-cell"
  | "table-column"
  | "table-column-group"
  | "table-footer-group"
  | "table-header-group"
  | "table-row-group"
  | "table-row"
  | "flow-root"
  | "grid"
  | "inline-grid"
  | "contents"
  | "list-item"
  | "hidden"
  | "float"
  | "clear"
  | "isolation"
  | "object"
  | "overflow"
  | "overscroll"
  | "static"
  | "fixed"
  | "absolute"
  | "relative"
  | "sticky"
  | "inset"
  | "start"
  | "end"
  | "top"
  | "right"
  | "bottom"
  | "left"
  | "visible"
  | "invisible"
  | "collapse"
  | "z"
  | "basis"
  | "grow"
  | "shrink"
  | "order"
  | "col"
  | "row"
  | "auto-cols"
  | "auto-rows"
  | "gap"
  | "justify"
  | "justify-items"
  | "justify-self"
  | "content"
  | "items"
  | "self"
  | "place-content"
  | "place-items"
  | "place-self"
  | "p"
  | "m"
  | "space"
  | "w"
  | "min-w"
  | "max-w"
  | "h"
  | "min-h"
  | "max-h"
  | "font"
  | "text"
  | "antialiased"
  | "subpixel-antialiased"
  | "italic"
  | "not-italic"
  | "normal-nums"
  | "ordinal"
  | "slashed-zero"
  | "lining-nums"
  | "oldstyle-nums"
  | "proportional-nums"
  | "tabular-nums"
  | "diagonal-fractions"
  | "stacked-fractions"
  | "tracking"
  | "line-clamp"
  | "leading"
  | "list-image"
  | "list"
  | "c"
  | "underline"
  | "overline"
  | "line-through"
  | "no-underline"
  | "decoration"
  | "uppercase"
  | "lowercase"
  | "capitalize"
  | "normal-case"
  | "truncate"
  | "indent"
  | "align"
  | "whitespace"
  | "break"
  | "hyphens"
  | "content"
  | "bg"
  | "from"
  | "rounded"
  | "border"
  | "b"
  | "divide"
  | "outline"
  | "ring"
  | "shadow"
  | "op"
  | "mix-blend"
  | "blur"
  | "brightness"
  | "constrast"
  | "drop-shadow"
  | "grayscale"
  | "hue-rotate"
  | "invert"
  | "saturate"
  | "sepia"
  | "backdrop"
  | "caption"
  | "transition"
  | "duration"
  | "ease"
  | "delay"
  | "animate"
  | "scale"
  | "rotate"
  | "translate"
  | "skew"
  | "origin"
  | "accent"
  | "appearance"
  | "cursor"
  | "caret"
  | "pointer-events"
  | "resize"
  | "scroll"
  | "snap"
  | "touch"
  | "select"
  | "will-change";

export {};
